services:
  - type: web
    name: mia-campus-web
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_APP_NAME
        value: MIA Campus
      - key: NEXT_PUBLIC_COMPANY_NAME
        value: MIA Solutions Pvt. Ltd.
      - key: NEXT_PUBLIC_IS_TEST_SITE
        value: "true"
